### ISSUE TITLE
Errore quando si tenta di ripristinare la videoteca

### ISSUE THREAD

**Issue by xXTimmy89Xx** [kodiondemand/addon#351]
Quando si tenta di ripristinare la videoteca dalle impostazioni di KoD si riceve il seguente messaggio e il ripristino non va a buon fine

![screenshot00000](https://user-images.githubusercontent.com/53865707/135778960-c9f07dd2-38f5-4db5-aaad-1668eae1e5c3.png)

2021-10-04 02:34:46.751 T:14560   ERROR <general>: kod[launcher.run:330]:  ######## ERROR #########
2021-10-04 02:34:46.751 T:14560   ERROR <general>: kod[launcher.run:330]:  Traceback (most recent call last):
                                                     File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\platformcode\launcher.py", line 300, in run
                                                       itemlist = getattr(channel, item.action)(item)
                                                     File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\specials\setting.py", line 732, in restore_tools
                                                       service.update(path, p_dialog, i, t, serie, 3)
                                                     File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\service.py", line 45, in update
                                                       category = serie.category
                                                   AttributeError: 'NoneType' object has no attribute 'category'

[kodi.log](https://github.com/kodiondemand/addon/files/7274812/kodi.log)

**Comment by mac12m99** [comment]
Potresti inviare anche l'archivio che stai tentando di ripristinare? Sembra non riesca a leggere le info di una serie
Comunque sulla beta ho mandato un possibile fix che dovrebbe quantomeno evitare l'errore e andare avanti, fammi sapere.

**Comment by xXTimmy89Xx** [comment]
> Potresti inviare anche l'archivio che stai tentando di ripristinare? Sembra non riesca a leggere le info di una serie Comunque sulla beta ho mandato un possibile fix che dovrebbe quantomeno evitare l'errore e andare avanti, fammi sapere.

Anche senza inviarti l'archivio da installazione pulita basta aggiungere la serie X-file da altadefinizionecommunity e successivamente tentare il ripristino della videoteca per replicare l'errore, ho privato anche l'ipotetico fix sulla beta ma il problema sembra persistere

2021-10-12 20:55:56.450 T:11364   ERROR <general>: kod[launcher.run:330]:  ######## ERROR #########
2021-10-12 20:55:56.450 T:11364   ERROR <general>: kod[launcher.run:330]:  Traceback (most recent call last):
                                                     File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\platformcode\launcher.py", line 300, in run
                                                       itemlist = getattr(channel, item.action)(item)
                                                     File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\specials\setting.py", line 732, in restore_tools
                                                       service.update(path, p_dialog, i, t, serie, 3)
                                                     File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\service.py", line 48, in update
                                                       for channel, url in serie.library_urls.items():
                                                   AttributeError: 'str' object has no attribute 'items'
