### ISSUE TITLE
Rpi3 osmc 19 (matrix), streaming e server query non funzionano più

### ISSUE THREAD

**Issue by Githeo** [kodiondemand/addon#400]
Salve,
sono passato dalla versione 18.9  a 19.5 di Osmc per Rpi3 e da allora streaming e ricerca sui vari canali non funzionano più.
E' per caso un problema relativo alla versione di python (adesso 3)?

A parte gli streaming che non partono più, anche le query ai vari server sembrano non ritornare niente.
Qui sotto il log quando vado in news->movies

```
2022-11-01 18:56:48.272 T:890      INFO <general>: CActiveAESink::OpenSink - initialize sink
2022-11-01 18:56:48.273 T:890      INFO <general>: CAESinkALSA::Initialize - Attempting to open device "@"
2022-11-01 18:56:48.287 T:890      INFO <general>: CAESinkALSA::Initialize - Opened device "sysdefault"
2022-11-01 18:56:48.293 T:890      INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2022-11-01 18:56:48.294 T:890      INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3
2022-11-01 18:56:48.300 T:2974     INFO <general>: initializing python engine.
2022-11-01 18:56:49.448 T:2974     INFO <general>: kod[default.<module>:20]:  init...
2022-11-01 18:56:51.601 T:2974     INFO <general>: kod[httptools.load_cookies:144]:  Reading cookies file
2022-11-01 18:56:52.799 T:2977     INFO <general>: kod[altadefinizione01.newest:123]:  peliculas
2022-11-url= 'https://www.altadefinizione01.sbs'>: kod[altadefinizione01.peliculas:48]:  peliculas 
2022-11-01 18:56:52.814 T:2975    ERROR <general>: kod[news.get_newest:393]:  ######## ERROR #########
2022-11-01 18:56:52.815 T:2975    ERROR <general>: kod[news.get_newest:393]:  No se pueden recuperar novedades de: 1337x
2022-11-01 18:56:52.826 T:2985    ERROR <general>: kod[news.get_newest:393]:  ######## ERROR #########
2022-11-01 18:56:52.827 T:2985    ERROR <general>: kod[news.get_newest:393]:  No se pueden recuperar novedades de: tantifilm
2022-11-01 18:56:52.829 T:2983     INFO <general>: kod[ilgeniodellostreaming_cam.newest:73]:  peliculas
2022-11-01 18:56:52.835 T:2975    ERROR <general>: kod[news.get_newest:395]:  ######## ERROR #########
2022-11-01 18:56:52.835 T:2975    ERROR <general>: kod[news.get_newest:395]:  Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.kod/specials/news.py", line 373, in get_newest
                                                       list_result = modulo.newest(categoria)
                                                   AttributeError: module 'channels.1337x' has no attribute 'newest'
                                                   
2022-11-01 18:56:52.840 T:2979     INFO <general>: kod[cineblog01.newest:57]:  peliculas
2022-11-01 18:56:52.844 T:2985    ERROR <general>: kod[news.get_newest:395]:  ######## ERROR #########
2022-11-01 18:56:52.845 T:2985    ERROR <general>: kod[news.get_newest:395]:  Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.kod/specials/news.py", line 373, in get_newest
                                                       list_result = modulo.newest(categoria)
                                                     File "/home/osmc/.kodi/addons/plugin.video.kod/core/support.py", line 511, in wrapper
                                                       item = args['item']
                                                   KeyError: 'item'
                                                   
2022-11-01 18:56:52.849 T:2986     INFO <general>: kod[toonitalia.newest:43]:  peliculas
2022-11-01 18:56:53.247 T:2980    ERROR <general>: kod[cinemalibero.newest:202]:  ######## ERROR #########
2022-11-01 18:56:53.248 T:2980    ERROR <general>: kod[cinemalibero.newest:202]:  newest log:  <class 'platformcode.logger.WebErrorException'>
2022-11-01 18:56:53.248 T:2980    ERROR <general>: kod[cinemalibero.newest:202]:  ######## ERROR #########
2022-11-01 18:56:53.248 T:2980    ERROR <general>: kod[cinemalibero.newest:202]:  newest log:  
2022-11-01 18:56:53.248 T:2980    ERROR <general>: kod[cinemalibero.newest:202]:  ######## ERROR #########
2022-11-01 18:56:53.248 T:2980    ERROR <general>: kod[cinemalibero.newest:202]:  newest log:  <traceback object at 0x4e3d3928>
2022-11-01 18:56:53.388 T:2980     INFO <general>: kod[jsontools.update_node:151] 
2022-11-01 18:56:53.555 T:2982     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: filmstreaming.media = 104.21.77.91
2022-11-01 18:56:53.557 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:53.566 T:2978     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: casacinema.lol = 188.114.96.2
2022-11-01 18:56:53.631 T:2986     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://toonitalia.co
2022-11-01 18:56:53.635 T:2986    ERROR <general>: kod[toonitalia.newest:54]:  ######## ERROR #########
2022-11-01 18:56:53.635 T:2986    ERROR <general>: kod[toonitalia.newest:54]:  <class 'platformcode.logger.WebErrorException'>
2022-11-01 18:56:53.635 T:2986    ERROR <general>: kod[toonitalia.newest:54]:  ######## ERROR #########
2022-11-01 18:56:53.636 T:2986    ERROR <general>: kod[toonitalia.newest:54]:  
2022-11-01 18:56:53.636 T:2986    ERROR <general>: kod[toonitalia.newest:54]:  ######## ERROR #########
2022-11-01 18:56:53.636 T:2986    ERROR <general>: kod[toonitalia.newest:54]:  <traceback object at 0x4d3b26a8>
2022-11-01 18:56:53.642 T:2981     INFO <general>: kod[jsontools.update_node:151] 
2022-11-01 18:56:53.645 T:2977     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://www.altadefinizione01.sbs
2022-11-01 18:56:53.652 T:2977    ERROR <general>: kod[altadefinizione01.newest:139]:  ######## ERROR #########
2022-11-01 18:56:53.653 T:2977    ERROR <general>: kod[altadefinizione01.newest:139]:  <class 'platformcode.logger.WebErrorException'>
2022-11-01 18:56:53.653 T:2977    ERROR <general>: kod[altadefinizione01.newest:139]:  ######## ERROR #########
2022-11-01 18:56:53.653 T:2977    ERROR <general>: kod[altadefinizione01.newest:139]:  
2022-11-01 18:56:53.653 T:2977    ERROR <general>: kod[altadefinizione01.newest:139]:  ######## ERROR #########
2022-11-01 18:56:53.653 T:2977    ERROR <general>: kod[altadefinizione01.newest:139]:  <traceback object at 0x4ea7e068>
2022-11-01 18:56:53.658 T:2986     INFO <general>: kod[jsontools.update_node:151] 
2022-11-01 18:56:53.675 T:2981     INFO <general>: Skipped 1 duplicate messages..
2022-11-01 18:56:53.675 T:2981     INFO <general>: kod[filmpertutti.newest:129] 
2022-11-01 18:56:53.677 T:2981     INFO <general>: kod[filmpertutti.peliculas:37] 
2022-11-01 18:56:53.689 T:2979     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://cb01.school//lista-film-ultimi-100-film-aggiunti/
2022-11-01 18:56:53.692 T:2979     INFO <general>: kod[support.wrapper:579]:  running findhost channels.cineblog01
2022-11-01 18:56:53.711 T:2983     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://ilgeniodellostreaming.sbs/film/
2022-11-01 18:56:53.726 T:2976     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://altadefinizione.nuovo.live
2022-11-01 18:56:53.731 T:2976     INFO <general>: kod[jsontools.update_node:151] 
2022-11-01 18:56:53.745 T:2983     INFO <general>: kod[ilgeniodellostreaming_cam.newest:87]:  <class 'platformcode.logger.WebErrorException'>
2022-11-01 18:56:53.745 T:2983     INFO <general>: kod[ilgeniodellostreaming_cam.newest:87]:  
2022-11-01 18:56:53.746 T:2983     INFO <general>: kod[ilgeniodellostreaming_cam.newest:87]:  <traceback object at 0x50abe8c8>
2022-11-01 18:56:53.752 T:2983     INFO <general>: kod[jsontools.update_node:151] 
2022-11-01 18:56:53.770 T:2976    ERROR <general>: kod[news.get_newest:393]:  ######## ERROR #########
2022-11-01 18:56:53.771 T:2976    ERROR <general>: kod[news.get_newest:393]:  No se pueden recuperar novedades de: altadefinizione
2022-11-01 18:56:53.771 T:2976    ERROR <general>: kod[news.get_newest:395]:  ######## ERROR #########
2022-11-01 18:56:53.771 T:2976    ERROR <general>: kod[news.get_newest:395]:  Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.kod/specials/news.py", line 373, in get_newest
                                                       list_result = modulo.newest(categoria)
                                                   AttributeError: module 'channels.altadefinizione' has no attribute 'newest'
                                                   
2022-11-01 18:56:53.774 T:2981     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: /category/film/
2022-11-01 18:56:53.777 T:2981     INFO <general>: kod[support.wrapper:579]:  running findhost channels.filmpertutti
2022-11-01 18:56:53.786 T:2987     INFO <general>: kod[vvvvid.loadjs:281]:  Json URL; https://www.vvvvid.it/vvvvid/ondemand/film/channel/10007/last/?full=true
2022-11-01 18:56:53.787 T:2987    ERROR <general>: kod[news.get_newest:393]:  ######## ERROR #########
2022-11-01 18:56:53.788 T:2987    ERROR <general>: kod[news.get_newest:393]:  No se pueden recuperar novedades de: vvvvid
2022-11-01 18:56:53.853 T:2979    ERROR <general>: kod[cineblog01.newest:73]:  ######## ERROR #########
2022-11-01 18:56:53.854 T:2979    ERROR <general>: kod[cineblog01.newest:73]:  <class 'platformcode.logger.ChannelScraperException'>
2022-11-01 18:56:53.854 T:2979    ERROR <general>: kod[cineblog01.newest:73]:  ######## ERROR #########
2022-11-01 18:56:53.854 T:2979    ERROR <general>: kod[cineblog01.newest:73]:  
2022-11-01 18:56:53.854 T:2979    ERROR <general>: kod[cineblog01.newest:73]:  ######## ERROR #########
2022-11-01 18:56:53.854 T:2979    ERROR <general>: kod[cineblog01.newest:73]:  <traceback object at 0x4bf51548>
2022-11-01 18:56:53.863 T:2987    ERROR <general>: kod[news.get_newest:395]:  ######## ERROR #########
2022-11-01 18:56:53.863 T:2987    ERROR <general>: kod[news.get_newest:395]:  Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.kod/specials/news.py", line 373, in get_newest
                                                       list_result = modulo.newest(categoria)
                                                     File "/home/osmc/.kodi/addons/plugin.video.kod/channels/vvvvid.py", line 103, in newest
                                                       return peliculas(item)
                                                     File "/home/osmc/.kodi/addons/plugin.video.kod/channels/vvvvid.py", line 116, in peliculas
                                                       json_file=loadjs(item.url + item.args)
                                                     File "/home/osmc/.kodi/addons/plugin.video.kod/channels/vvvvid.py", line 282, in loadjs
                                                       json = current_session.get(url, headers=headers, params=payload).json()
                                                   NameError: name 'payload' is not defined
                                                   
2022-11-01 18:56:53.875 T:2979     INFO <general>: kod[jsontools.update_node:151] 
2022-11-01 18:56:53.889 T:2982     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: filmstreaming.bond = 104.21.43.234
2022-11-01 18:56:53.902 T:2981     INFO <general>: kod[jsontools.update_node:151] 
2022-11-01 18:56:53.932 T:2981     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: /category/film/
2022-11-01 18:56:53.934 T:2981     INFO <general>: kod[filmpertutti.newest:150]:  <class 'platformcode.logger.WebErrorException'>
2022-11-01 18:56:53.934 T:2981     INFO <general>: kod[filmpertutti.newest:150]:  
2022-11-01 18:56:53.934 T:2981     INFO <general>: kod[filmpertutti.newest:150]:  <traceback object at 0x4f8bfd88>
2022-11-01 18:56:53.936 T:2981     INFO <general>: kod[jsontools.update_node:151] 
2022-11-01 18:56:54.134 T:2982     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: filmstreaming.shop = 188.114.97.2
2022-11-01 18:56:54.379 T:2982     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: filmstreaming.cfd = 172.67.179.87
2022-11-01 18:56:54.384 T:2978     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://casacinema.lol/category/film
2022-11-01 18:56:54.409 T:2978     INFO <general>: kod[casacinema.newest:88]:  <class 'IndexError'>
2022-11-01 18:56:54.409 T:2978     INFO <general>: kod[casacinema.newest:88]:  list index out of range
2022-11-01 18:56:54.409 T:2978     INFO <general>: kod[casacinema.newest:88]:  <traceback object at 0x4d257428>
2022-11-01 18:56:54.413 T:2978     INFO <general>: kod[jsontools.update_node:151] 
2022-11-01 18:56:54.446 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/film
2022-11-01 18:56:54.851 T:2982     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: filmstreaming.store = 172.67.157.204
2022-11-01 18:56:55.284 T:2982     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: filmstreaming.skin = 188.114.97.2
2022-11-01 18:56:55.285 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:55.519 T:2982     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://filmstreaming.media
2022-11-01 18:56:55.585 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5762
2022-11-01 18:56:55.593 T:2982     INFO <general>: kod[jsontools.update_node:151] 
2022-11-01 18:56:55.634 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:55.841 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5761
2022-11-01 18:56:55.882 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:56.105 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5753
2022-11-01 18:56:56.144 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:56.433 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5752
2022-11-01 18:56:56.470 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:56.800 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5751
2022-11-01 18:56:56.837 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:57.061 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5749
2022-11-01 18:56:57.097 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:57.304 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5745
2022-11-01 18:56:57.341 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:57.560 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5743
2022-11-01 18:56:57.596 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:57.872 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5741
2022-11-01 18:56:57.910 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:58.117 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5737
2022-11-01 18:56:58.155 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:58.428 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5736
2022-11-01 18:56:58.475 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:58.715 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5735
2022-11-01 18:56:58.750 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:58.968 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5733
2022-11-01 18:56:59.004 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:59.273 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5730
2022-11-01 18:56:59.310 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:59.532 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5729
2022-11-01 18:56:59.567 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:56:59.777 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5728
2022-11-01 18:56:59.813 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:57:00.029 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5727
2022-11-01 18:57:00.065 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:57:00.288 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5726
2022-11-01 18:57:00.323 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:57:00.550 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5723
2022-11-01 18:57:00.586 T:2984     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:57:00.819 T:2984     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5722
2022-11-01 18:57:00.908 T:3003     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:57:01.256 T:3002     INFO <general>: Skipped 7 duplicate messages..
2022-11-01 18:57:01.256 T:3002     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5762
2022-11-01 18:57:01.306 T:3002     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:57:01.325 T:3005     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5752
2022-11-01 18:57:01.384 T:3005     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:57:01.401 T:3004     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5753
2022-11-01 18:57:01.424 T:3003     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5761
2022-11-01 18:57:01.480 T:3004     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:57:01.526 T:3006     INFO <general>: Skipped 1 duplicate messages..
2022-11-01 18:57:01.526 T:3006     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5751
2022-11-01 18:57:01.551 T:3007     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5749
2022-11-01 18:57:01.582 T:3008     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5745
2022-11-01 18:57:01.626 T:3009     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5743
2022-11-01 18:57:01.714 T:3006     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:57:01.733 T:3002     INFO <general>: Skipped 1 duplicate messages..
2022-11-01 18:57:01.733 T:3002     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5741
2022-11-01 18:57:01.766 T:3005     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5737
2022-11-01 18:57:01.834 T:3008     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:57:01.901 T:3004     INFO <general>: Skipped 3 duplicate messages..
2022-11-01 18:57:01.901 T:3004     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5736
2022-11-01 18:57:01.998 T:3004     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:57:02.030 T:3003     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5735
2022-11-01 18:57:02.102 T:3003     INFO <general>: kod[resolverdns.getIp:79]:  Cache DNS: streamingcommunity.city = 172.67.202.113
2022-11-01 18:57:02.152 T:3002     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5727
2022-11-01 18:57:02.193 T:3008     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5729
2022-11-01 18:57:02.256 T:3006     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5733
2022-11-01 18:57:02.285 T:3007     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5730
2022-11-01 18:57:02.316 T:3009     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5728
2022-11-01 18:57:02.354 T:3005     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5726
2022-11-01 18:57:02.392 T:3004     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5723
2022-11-01 18:57:02.430 T:3003     INFO <general>: kod[httptools.downloadpage:461]:  Page URL: https://streamingcommunity.city/api/titles/preview/5722
2022-11-01 18:57:02.574 T:3010    ERROR <general>: kod[tmdb.wrapper:151]:  ######## ERROR #########
2022-11-01 18:57:02.575 T:3010    ERROR <general>: kod[tmdb.wrapper:151]:  error in: An exception of type UnicodeDecodeError occured. Arguments:
                                                   ('ascii', b'\x07\xe6\n\x19\r)\x14\x07\xf3\xc2', 1, 2, 'ordinal not in range(128)')
```

**Comment by mac12m99** [comment]
Salve,
potresti provare vari menu e mandare il log completo? (con il logging di debug dell'addon abilitato -> impostazioni di KoD)
Tutti gli errori presenti nel pezzetto che hai mandato non dovrebbero essere bloccanti.

**Comment by Githeo** [comment]
Salve,
reinstallando KoD lo stesso non arrivava a recuperare i link.
Cancellando la cartella ~/.kodi e reinstallando KoD adesso è tornato a funzionare.
Guardando i nuovi log sembra che nei precedenti manchi la parte di DNS lookup per qualche ragione.
