### ISSUE TITLE
module 'xbmc' has no attribute 'translatePath'

### ISSUE THREAD

**Issue by Zawardo1000** [kodiondemand/addon#408]
Scenario Kodi 20 su android.
Provando a usare il menu contestuale dalla videoteca (opzioni kod) da errore.
Guardando il log è questo:

2023-01-22 16:16:33.056 T:2188    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/contextmenu.py", line 1, in <module>
                                                       from platformcode import config, logger
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/config.py", line 18, in <module>
                                                       changelogFile = xbmc.translatePath("special://profile/addon_data/plugin.video.kod/changelog.txt")
                                                                       ^^^^^^^^^^^^^^^^^^
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--

Ho provato a importare xbmcvfs in contextmenu.py, config.py, search.py, tvshow_options.py e sostituirlo a tappeto nel codice ma ora da questo errore:

2023-01-22 17:08:08.675 T:8464    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'posixpath' has no attribute 'listdir'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/contextmenu.py", line 63, in <module>
                                                       build_menu()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/contextmenu.py", line 42, in build_menu
                                                       module_item_actions = module.get_menu_items()
                                                                             ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/contextmenu/tvshow_options.py", line 132, in get_menu_items
                                                       if check_condition():
                                                          ^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/contextmenu/tvshow_options.py", line 126, in check_condition
                                                       path = search_paths(get_id())
                                                              ^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/contextmenu/tvshow_options.py", line 50, in search_paths
                                                       records = execute_sql('SELECT idPath FROM tvshowlinkpath WHERE idShow LIKE "%s"' % Id)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/contextmenu/tvshow_options.py", line 73, in execute_sql
                                                       for f in os.path.listdir(xbmcvfs.translatePath("special://userdata/Database")):
                                                                ^^^^^^^^^^^^^^^
                                                   AttributeError: module 'posixpath' has no attribute 'listdir'
                                                   -->End of Python script error report<--

Quindi probabilmente xbmcvfs non era la soluzione migliore...
Comunque per sintetizzare non funziona il menu contestuale sulla videoteca (fuori da kod) e kodi 20.

**Comment by xXTimmy89Xx** [comment]
Ciao @Zawardo1000 Credo tu intenda dalla libreria, comunque dovrebbe essere stato fixato con il commit 1ce00b4.

**Comment by Zawardo1000** [comment]
Confermo. Grazie!
