### ISSUE TITLE
Link CB01 non corretto

### ISSUE THREAD

**Issue by Masmar25** [kodiondemand/addon#444]
Ciao,
il link a CB01 non sembra essere riconosciuto correttamente.
Da KOD il canale si apre correttamente (Film->CB01) e le sezioni esistono effettivamente sul sito (es. ultimi 100 film aggiunti), ma cliccando si genera un errore.

Da profano quel che capisco è che tenta di connettersi a https://cb01.training e fallendo riprova con https://cb01.uno (fallendo di nuovo).
L'indirizzo https://cb01.training penso il risultato di un tentativo di ottenerlo dinamicamente ma non ho capito come venga recuperato . Sono coinvolti [findhost](https://github.com/kodiondemand/addon/blob/master/channels/cineblog01.py#L11) e [downloadpage](https://github.com/kodiondemand/addon/blob/master/core/httptools.py#L227).
Se non sbaglio Cineblog non usa più https://cb01.uno per mantenere il link aggiornato (credo ne abbiano introdotti altri, io personalmente da pc uso il feed https://feedly.com/#subscription/feed/https://cb01.uno/feed/).

Spero di essere stato il più chiaro possibile, ho cercato di spiegare al meglio delle mie possibilità.
Grazie per questo fantastico addon.

```
2023-11-13 15:38:26.884 T:15527    info <general>: kod[httptools.show_infobox:199]:  ┌────────────────────────────────────────────────────────────────────────────────────────────────────┐
2023-11-13 15:38:26.885 T:15527    info <general>: kod[httptools.show_infobox:200]:  │                                   Kodi on Demand: 1.7.7 f8c8b2b                                    │
2023-11-13 15:38:26.885 T:15527    info <general>: kod[httptools.show_infobox:201]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.885 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Timeout: 15                                                                                         │
2023-11-13 15:38:26.885 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.886 T:15527    info <general>: kod[httptools.show_infobox:218]:  │URL: https://cb01.training//ultimi-100-film-aggiunti/                                               │
2023-11-13 15:38:26.886 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.886 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Domain: cb01.training                                                                               │
2023-11-13 15:38:26.886 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.887 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Petition: GET                                                                                       │
2023-11-13 15:38:26.887 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.887 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Download Page: True                                                                                 │
2023-11-13 15:38:26.887 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.888 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Use cookies: True                                                                                   │
2023-11-13 15:38:26.888 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.889 T:15527    info <general>: kod[httptools.show_infobox:216]:  │Cookie file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.v│
2023-11-13 15:38:26.889 T:15527    info <general>: kod[httptools.show_infobox:216]:  │ideo.kod/cookies.dat                                                                                │
2023-11-13 15:38:26.890 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.890 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Cookies: <RequestsCookieJar[]>                                                                      │
2023-11-13 15:38:26.890 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.890 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Data Encoding: None                                                                                 │
2023-11-13 15:38:26.890 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.892 T:15527    info <general>: kod[httptools.show_infobox:216]:  │Response code: HTTPSConnectionPool(host='cb01.training', port=443): Max retries exceeded with url:  │
2023-11-13 15:38:26.893 T:15527    info <general>: kod[httptools.show_infobox:216]:  │//ultimi-100-film-aggiunti/ (Caused by                                                              │
2023-11-13 15:38:26.893 T:15527    info <general>: kod[httptools.show_infobox:216]:  │NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x6f5bf330>: Failed to    │
2023-11-13 15:38:26.894 T:15527    info <general>: kod[httptools.show_infobox:216]:  │establish a new connection: [Errno 7] No address associated with hostname'))                        │
2023-11-13 15:38:26.894 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.894 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Success: False                                                                                      │
2023-11-13 15:38:26.895 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.896 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Response data length: 0                                                                             │
2023-11-13 15:38:26.896 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.896 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Request Headers:                                                                                    │
2023-11-13 15:38:26.896 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.897 T:15527    info <general>: kod[httptools.show_infobox:216]:  │- User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)      │
2023-11-13 15:38:26.897 T:15527    info <general>: kod[httptools.show_infobox:216]:  │Chrome/119.0.6045.124 Safari/537.36                                                                 │
2023-11-13 15:38:26.897 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.898 T:15527    info <general>: kod[httptools.show_infobox:218]:  │- Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8     │
2023-11-13 15:38:26.898 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.898 T:15527    info <general>: kod[httptools.show_infobox:218]:  │- Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3                                              │
2023-11-13 15:38:26.898 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.898 T:15527    info <general>: kod[httptools.show_infobox:218]:  │- Accept-Charset: UTF-8                                                                             │
2023-11-13 15:38:26.899 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.900 T:15527    info <general>: kod[httptools.show_infobox:218]:  │- Accept-Encoding: gzip                                                                             │
2023-11-13 15:38:26.900 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.901 T:15527    info <general>: kod[httptools.show_infobox:218]:  │- Referer: https://cb01.training/                                                                   │
2023-11-13 15:38:26.901 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.901 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Response Headers:                                                                                   │
2023-11-13 15:38:26.901 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:26.902 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Finished in: 0.06505799293518066                                                                    │
2023-11-13 15:38:26.902 T:15527    info <general>: kod[httptools.show_infobox:222]:  └────────────────────────────────────────────────────────────────────────────────────────────────────┘
2023-11-13 15:38:26.906 T:15527    info <general>: kod[support.wrapper:581]:  running findhost channels.cineblog01
2023-11-13 15:38:26.906 T:15527    info <general>: kod[jsontools.get_node_from_file:80] 
2023-11-13 15:38:26.908 T:15527    info <general>: kod[jsontools.check_to_backup:119] 
2023-11-13 15:38:27.030 T:15527    info <general>: kod[httptools.show_infobox:167] 
2023-11-13 15:38:27.031 T:15527    info <general>: kod[httptools.show_infobox:199]:  ┌────────────────────────────────────────────────────────────────────────────────────────────────────┐
2023-11-13 15:38:27.031 T:15527    info <general>: kod[httptools.show_infobox:200]:  │                                   Kodi on Demand: 1.7.7 f8c8b2b                                    │
2023-11-13 15:38:27.032 T:15527    info <general>: kod[httptools.show_infobox:201]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:27.032 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Timeout: 15                                                                                         │
2023-11-13 15:38:27.032 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:27.032 T:15527    info <general>: kod[httptools.show_infobox:218]:  │URL: https://cb01.uno                                                                               │
2023-11-13 15:38:27.033 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:27.033 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Domain: cb01.uno                                                                                    │
2023-11-13 15:38:27.033 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:27.034 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Petition: GET                                                                                       │
2023-11-13 15:38:27.035 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:27.036 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Download Page: True                                                                                 │
2023-11-13 15:38:27.036 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:27.036 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Use cookies: True                                                                                   │
2023-11-13 15:38:27.037 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:27.037 T:15527    info <general>: kod[httptools.show_infobox:216]:  │Cookie file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.v│
2023-11-13 15:38:27.038 T:15527    info <general>: kod[httptools.show_infobox:216]:  │ideo.kod/cookies.dat                                                                                │
2023-11-13 15:38:27.038 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:27.038 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Success: False                                                                                      │
2023-11-13 15:38:27.038 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:27.040 T:15527    info <general>: kod[httptools.show_infobox:216]:  │Response code: HTTPSConnectionPool(host='cb01.uno', port=443): Max retries exceeded with url: /     │
2023-11-13 15:38:27.040 T:15527    info <general>: kod[httptools.show_infobox:216]:  │(Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x6f5bfdf0>:   │
2023-11-13 15:38:27.041 T:15527    info <general>: kod[httptools.show_infobox:216]:  │Failed to establish a new connection: [Errno 7] No address associated with hostname'))              │
2023-11-13 15:38:27.041 T:15527    info <general>: kod[httptools.show_infobox:220]:  ├────────────────────────────────────────────────────────────────────────────────────────────────────┤
2023-11-13 15:38:27.041 T:15527    info <general>: kod[httptools.show_infobox:218]:  │Finished in: 0.12029123306274414                                                                    │
2023-11-13 15:38:27.042 T:15527    info <general>: kod[httptools.show_infobox:222]:  └────────────────────────────────────────────────────────────────────────────────────────────────────┘
2023-11-13 15:38:27.077 T:15527   error <general>: kod[launcher.run:168]:  ######## ERROR #########
2023-11-13 15:38:27.077 T:15527   error <general>: kod[launcher.run:168]:  Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/core/support.py", line 584, in wrapper
                                                       host = config.get_channel_url(func.__globals__['findhost'], ch, True)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/config.py", line 127, in get_channel_url
                                                       url = findhostMethod(channels_data['findhost'][name])
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/channels/cineblog01.py", line 12, in findhost
                                                       host = httptools.downloadpage(url, follow_redirect=True).url
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   AttributeError: type object 'HTTPResponse' has no attribute 'url'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/launcher.py", line 150, in run
                                                       else: actions(item)
                                                             ^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/launcher.py", line 370, in actions
                                                       itemlist = getattr(channel, item.action)(item)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/core/support.py", line 590, in wrapper
                                                       raise logger.ChannelScraperException
                                                   platformcode.logger.ChannelScraperException
```

**Comment by mac12m99** [comment]
Ciao,
cb01.uno e .training funzionano e reindirizzano entrambi a https://cb01.yachts/.
Entrambi sono offuscati, quindi li puoi vedere solo con DNS internazionali, secondo me è qualcosa legato a ciò.
Per quanto riguarda l'addon in teoria dovrebbe forzare l'ultilizzo di quelli di Cloudflare, assicurati di avere "override DNS" attivo nelle impostazioni di KoD.

Hai qualche software attivo che potrebbe influire sui DNS?

**Comment by Masmar25** [comment]
Grazie! Il problema erano proprio i DNS, stupidamente non li ho ricontrollati.
In effetti li avevo impostati con quelli di Cloudflare sulla rete a cui mi connettevo, ma credo a causa di un aggiornamento sono tornati ai valori di default.
Interessante l'opzione "Override DNS", onestamente non l'avevo notata! Ho frugato il wiki in lungo e in largo, ma non credo sia documentata.
Cercando nello specifico vedo che è stata proposta come soluzione già parecchie volte, posso suggerire di documentarla esplicitamente nel wiki o di mettere il suggerimento ben visibile (es. FAQ)?

Grazie di nuovo, risolto!
