### ISSUE TITLE
Aggiornamento videoteca errore con python 3.12

### ISSUE THREAD

**Issue by PacoPuerta** [kodiondemand/addon#494]
Buongiorno, nell'ultimo aggiornamento _stable_ di Manjaro, python è stato aggirnato alla versione 3.12, e kodi alla versione 21. 

L'aggiornamento della videoteca (o qualsiasi operazione legata alla videoteca) genera un errore non permettendo l'aggiornamento della stessa.

Riporto il log dell'eccezzione:

```2024-05-25 17:11:56.075 T:106338    info <general>: kod[default.<module>:20]:  init...
2024-05-25 17:11:56.159 T:106338    info <general>: kod[launcher.run:33] 
2024-05-25 17:11:56.159 T:106338    info <general>: kod[launcher.makeItem:219] 
2024-05-25 17:11:56.159 T:106338    info <general>: kod[launcher.run:41]:  action= 'update_videolibrary', channel= 'videolibrary', infoLabels= {}
2024-05-25 17:11:56.160 T:106338    info <general>: kod[launcher.actions:368]:  Executing channel videolibrary method update_videolibrary
2024-05-25 17:11:56.269 T:106338    info <general>: kod[tmdb.cache_response:77] 
2024-05-25 17:11:56.271 T:106338    info <general>: kod[launcher.importChannel:363]:  Running channel specials.videolibrary | /home/[user]/.kodi/addons/plugin.video.kod/specials/videolibrary.py
2024-05-25 17:11:56.271 T:106338    info <general>: kod[videolibrary.update_videolibrary:611] 
2024-05-25 17:11:56.324 T:106338   error <general>: kod[launcher.run:168]:  ######## ERROR #########
2024-05-25 17:11:56.324 T:106338   error <general>: kod[launcher.run:168]:  Traceback (most recent call last):
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/platformcode/launcher.py", line 150, in run
                                                       else: actions(item)
                                                             ^^^^^^^^^^^^^
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/platformcode/launcher.py", line 370, in actions
                                                       itemlist = getattr(channel, item.action)(item)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/specials/videolibrary.py", line 614, in update_videolibrary
                                                       import service
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/service.py", line 30, in <module>
                                                       from servers import torrent
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/servers/torrent.py", line 8, in <module>
                                                       from lib.guessit import guessit
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/lib/guessit/__init__.py", line 8, in <module>
                                                       from .api import guessit, GuessItApi
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/lib/guessit/api.py", line 20, in <module>
                                                       from .rules import rebulk_builder
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/lib/guessit/rules/__init__.py", line 11, in <module>
                                                       from .properties.episodes import episodes
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/lib/guessit/rules/properties/episodes.py", line 14, in <module>
                                                       from guessit.rules import match_processors
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/lib/guessit/__init__.py", line 8, in <module>
                                                       from .api import guessit, GuessItApi
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/lib/guessit/api.py", line 20, in <module>
                                                       from .rules import rebulk_builder
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/lib/guessit/rules/__init__.py", line 18, in <module>
                                                       from .properties.date import date
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/lib/guessit/rules/properties/date.py", line 8, in <module>
                                                       from ..common.date import search_date, valid_year
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/lib/guessit/rules/common/date.py", line 6, in <module>
                                                       from dateutil import parser
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/lib/dateutil/parser/__init__.py", line 2, in <module>
                                                       from ._parser import parse, parser, parserinfo, ParserError
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/lib/dateutil/parser/_parser.py", line 50, in <module>
                                                       from .. import tz
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/lib/dateutil/tz/__init__.py", line 2, in <module>
                                                       from .tz import *
                                                     File "/home/[user]/.kodi/addons/plugin.video.kod/lib/dateutil/tz/tz.py", line 21, in <module>
                                                       from six.moves import _thread
                                                   ModuleNotFoundError: No module named 'six.moves'```

**Comment by xXTimmy89Xx** [comment]
il problema dovrebbe essere stato risolto con il commit c655e52
